### ISSUE TITLE
correct version of create fabric is not available for download

### ISSUE THREAD

**Issue by KaptainQKool** [rhysdh540/create-unlimited#7]
### Minecraft Mod Loader

Fabric

### Minecraft Version

1.18.2

### Mod Version

0.2

### Description of bug

the only create version compatible with this mod on fabric 1.18.2 (0.5.0g build 836) is not available for download (as far as i am aware)

### Steps to reproduce

1. download this mod and the latest version of create fabric 0.5.0g for 1.18.2
2. launch the game
3. notice the error message: ntl requires create fabric 0.5.0g build 836
4. pull up versions for create fabric on curseforge or modrinth
5. notice that the required version is not present, despite the fact that versions beyond 0.5.0g are available (ergo: "wait" may not be a plausible solution)
![Screenshot 2023-02-02 at 20-32-49 Create Fabric - Versions](https://user-images.githubusercontent.com/110294153/216490033-d41f09b3-83e5-444e-9d94-68b866c82f67.png)

**Comment by rhysdh540** [comment]
I’m getting around to that, should be fixed soon.

**Comment by KaptainQKool** [comment]
Update: still happening for latest fabric 1.18.2 build: required version is 929, latest version available is 921
